before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
  - sudo apt-get install libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev
script:
  - rustc src/sdl/lib.rs
  - rustc src/sdl_mixer/lib.rs
  - rustc src/sdl_image/lib.rs
